### ISSUE TITLE
Whiteboard text text input bug

### ISSUE THREAD

**Issue by DasGabelhauser** [cubixel/TutorPoint#62]
following the steps
- set text to draw
- select text
- draw some text
- set text to draw to some new value
- deselect text
- draw some text

should draw one entry of each value, but instead draws them both as the first value

**Comment by dmb537** [comment]
More accurately described as "No idle state for tool - always uses last selected tool" (changing text while tool is selected works fine, and having no tool selected just repeats the last thing). Fixed by adding "idle" state to pointer.

Fixed in Daniel branch.
