### ISSUE TITLE
Presentation Sharing ghost of previous presentation issue

### ISSUE THREAD

**Issue by DasGabelhauser** [cubixel/TutorPoint#85]
occasionally, when a student joins a stream, they will not download the presentation properly.

from testing report:
TS1 was in stream with CT with presentation#1 loaded. TS1 then disconnected, and CT changed presentation to presentation#2, the one intended to be used for this test. When TS1 rejoined, logs behaved as if presentation#1 was loaded.

TS1 showed grey screen as if no presentation was loaded, however.

**Comment by dmb537** [comment]
I believe this was caused by an issue with multiple PresentationWindowControllers being created, resolved recently. Presumed fixed.
